name: code analysis & formatting

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.7.1
        with:
          java-version: 17
          distribution: temurin
      - uses: subosito/flutter-action@v2.20.0
        with:
          cache: true
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
      - name: Linter
        run: flutter analyze
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.7.1
        with:
          java-version: 17
          distribution: temurin
      - uses: subosito/flutter-action@v2.20.0
        with:
          cache: true
      - name: Format
        run: dart format --set-exit-if-changed .
